FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Possibility to remove this line if volumes are used in docker-compose
# If the dev only reused the Dockerfile, this line is important 
# Or this file can be the model for the Dockerfile (for production)
COPY . .

CMD [ "npm", "run", "start" ]