FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Possibility to remove this line if volumes are used in docker-compose
# If the dev only reused the Dockerfile, this line is important 
# Or this file can be the model for the Dockerfile (for production)
COPY . .

CMD [ "npm", "run", "start" ]


########################################################
## Comands to use in terminal
## docker build -f Dockerfile.dev . --> build a image with this Dockerfile.dev
## docker run -p 8080:80 <container_id>
## Start web browser with "localhost:8080"
########################################################